'use client';
import { useMemo, useState } from 'react';
import { Menu, Plus, Search, Settings, MessageSquare, Paperclip, Globe, Sparkles, Mic, ArrowUp, MoreHorizontal, Home, Image as ImageIcon, SlidersHorizontal, UserCircle, Download, Languages, Shield, Info, RefreshCw, X } from 'lucide-react';

type Message={role:'user'|'assistant',content:string};
const initial:Message[]=[{role:'assistant',content:'Hi! I’m ElitePlus. How can I help you today?'}];
const chats=['Build a portfolio website','Explain quantum computing','Weekend meal ideas','Study plan for calculus','Travel itinerary for Japan'];
export default function HomePage(){
 const [messages,setMessages]=useState(initial); const [input,setInput]=useState(''); const [open,setOpen]=useState(false); const [settings,setSettings]=useState(false); const [model,setModel]=useState('ElitePlus 5'); const [loading,setLoading]=useState(false);
 const suggestions=useMemo(()=>['Write a plan','Help me brainstorm','Explain a topic','Create a checklist'],[]);
 const send=(text=input)=>{const t=text.trim(); if(!t||loading)return; setInput(''); setMessages(m=>[...m,{role:'user',content:t}]); setLoading(true); setTimeout(()=>{setMessages(m=>[...m,{role:'assistant',content:`I can help with “${t}”. This demo is connected to a local response loop, so you can try the full chat flow without an API key.`}]);setLoading(false)},700)};
 return <div className="appShell"><div className="wallpaper" /><div className="grain" />
  <aside className={open?'sidebar glass open':'sidebar glass'}><div className="sideTop"><button className="iconBtn glassBtn" onClick={()=>setOpen(false)} aria-label="Close sidebar"><X size={19}/></button><button className="newChat glassBtn" onClick={()=>setMessages(initial)}><Plus size={18}/> New chat</button></div>
   <div className="search glassInset"><Search size={17}/><input placeholder="Search chats"/></div><div className="sectionLabel">Recent</div><div className="chatList">{chats.map((c,i)=><button className={i===0?'chat active':'chat'} key={c}><MessageSquare size={16}/><span>{c}</span><MoreHorizontal size={16} className="more"/></button>)}</div>
   <div className="sideBottom"><button onClick={()=>setSettings(true)}><Settings size={17}/> Settings</button><button><Sparkles size={17}/> Customize</button><div className="profile"><div className="avatar">E</div><div><b>Guest</b><small>Free plan</small></div><MoreHorizontal size={17}/></div></div></aside>
  <main className="main glass"><header className="header"><button className="iconBtn glassBtn mobileMenu" onClick={()=>setOpen(true)}><Menu size={20}/></button><div className="brand"><div className="brandMark">✦</div><div><b>ElitePlus</b><span>AI assistant</span></div></div><div className="headerActions"><button className="roundBtn glassBtn" title="Refresh" onClick={()=>setMessages(initial)}><RefreshCw size={18}/></button><button className="roundBtn glassBtn" title="Info"><Info size={18}/></button><button className="roundBtn glassBtn" title="Settings" onClick={()=>setSettings(v=>!v)}><Settings size={18}/></button></div></header>
   <div className="modelBar"><div className="modelWrap glassInset"><Sparkles size={15}/><select value={model} onChange={e=>setModel(e.target.value)}><option>ElitePlus 5</option><option>ElitePlus 5 Fast</option><option>ElitePlus 4</option></select><span className="chev">⌄</span></div></div>
   <div className="messages">{messages.map((m,i)=><div className={'row '+m.role} key={i}><div className={m.role==='assistant'?'botAvatar':'userAvatar'}>{m.role==='assistant'?'✦':'E'}</div><div className="bubble">{m.content}</div></div>)}{loading&&<div className="row assistant"><div className="botAvatar">✦</div><div className="bubble dots"><i></i><i></i><i></i></div></div>}</div>
   <div className="composerArea"><div className="suggestions">{suggestions.map(s=><button key={s} className="glassInset" onClick={()=>send(s)}>{s}</button>)}</div><div className="composer glassInset"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message ElitePlus..." rows={1}/><div className="composeTools"><div><button title="Attach"><Paperclip size={18}/></button><button title="Web"><Globe size={18}/></button></div><div><button title="Voice"><Mic size={18}/></button><button className="send" onClick={()=>send()} disabled={!input.trim()||loading}><ArrowUp size={18}/></button></div></div></div><p className="disclaimer">ElitePlus can make mistakes. Check important information.</p></div>
  </main><nav className="bottomNav glass"><button className="active"><Home size={21}/><span>Home</span></button><button><SlidersHorizontal size={21}/><span>Tools</span></button><button onClick={()=>setSettings(true)}><Settings size={21}/><span>Settings</span></button></nav>
  {settings&&<div className="settingsPanel glass"><div className="panelTitle"><b>App appearance</b><button className="iconBtn glassBtn" onClick={()=>setSettings(false)}><X size={18}/></button></div><div className="settingRow"><Sparkles/><div><b>Liquid Glass</b><small>Soft translucent panels and blur</small></div></div><div className="settingRow"><ImageIcon/><div><b>Wallpaper</b><small>Background image and blur</small></div></div><div className="settingRow"><UserCircle/><div><b>Avatar</b><small>Change profile icon</small></div></div><div className="settingRow"><Download/><div><b>Chat data</b><small>Auto</small></div></div><div className="settingRow"><Languages/><div><b>Language</b><small>System</small></div></div><div className="settingRow"><Shield/><div><b>Privacy</b><small>Local demo data</small></div></div></div>}
 </div>;
}